name: Run unit & integration tests against Golang RC version
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: RC version check
    runs-on: ubuntu-latest
    # env:
    #   # COSMOS_CONNECTION_URL: ${{ secrets.COSMOS_CONNECTION_URL }}
    #   # COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run coverage commands
        shell: bash
        run: |
            #!/bin/bash

            echo "Dealing with Golang RC version!"
            rcToInstall=$(gvm listall | grep rc | grep 23 | tail -1 | tr -d ' ')
            echo "RC version : $rcToInstall"

          



