name: Run govulncheck
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  runGovulncheck:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          
      - name: Run govulncheck commands
        run: |
            #!/bin/bash

            set -euxo pipefail

            echo "::group::Go Environment"
            which go
            go version
            go env
            echo "::endgroup::"

            echo "::group::Install govulncheck"
            go install golang.org/x/vuln/cmd/govulncheck@latest

            export PATH="$(go env GOPATH)/bin:$PATH"

            which govulncheck
            govulncheck -version
            echo "::endgroup::"

            echo "::group::Run govulncheck"
            govulncheck -show verbose ./...
            echo "::endgroup::"
            
